### PR TITLE
fixes/tests

### PR DESCRIPTION
**Pull request by vonydev**
- Calling free() for buffers allocated by matrixSSL's psGetFileBuf() was wrong because Perl replaces malloc/free with its own macros and calling Perl's free() on a C malloc() results in an exception
- Tests for OCSP, CT, SNI
- Small fixes

### CODE REVIEW

**Comment by powerman** [comment]
Do you plan to make any more changes before release?

**Comment by vonydev** [comment]
No. Safe to release. What version will it be? 3.7.4?

**Comment by powerman** [comment]
Yep. I've asked @gitcnd to confirm release at Saturday, but he didn't replied yet - probably get tired of my emails. :smiling_imp: I'm going to release it tomorrow.

**Comment by powerman** [comment]
v3.7.4, actually.

**Pull request merged**
