### PR TITLE
Patches & fixes

### PR DESCRIPTION
**Pull request by vonydev**
See comments and changes for each

### CODE REVIEW

**Comment by powerman** [comment]
BTW, there was no needs in closing PR #13, if you update your branch used to make PR commits included in PR will be also automatically updated. So you can continue improving PR until it'll be merged - but you'll have to use different branches for different tasks if you don't wanna update PR with new unrelated commits.

**Comment by vonydev** [comment]
Got it. Now It fails again because of t/pod-coverage.t. Grr

**Comment by powerman** [comment]
Did you rebased your branch on my current master (or merge it, whatever you like)? I see changes which revert some of my commits (mostly cleanup for whitespaces etc.).

**Comment by vonydev** [comment]
I forked it this morning so whatever you did in the meantime doesn't show up.

**Comment by powerman** [comment]
Naming all patches like now is ok while no patches depends on another one and require to be applied in predefined order. To support this it's usually good idea to name patches like `01-feature.patch`, `02-fix-to-feature.patch`, etc.

Please let me know (by adding comment here) when you finish updating this PR (there should be no unintended changes - especially ones which revert my changes :smile: - here: https://github.com/powerman/perl-Crypt-MatrixSSL3/pull/14/files). Thanks.

**Comment by vonydev** [comment]
I don't like having patches to patches to patches to patches to ... So for me at least having one file with all the changes from the original is enough. If you think incremental patches are necessary feel free to add support.

I'll let you know when the white space is fixed.

**Comment by powerman** [comment]
> I don't like having patches to patches to patches

I don't like either. But sometimes patch to add feature B depends on availability of feature A, which should be added by another one patch. In this case it's not really "patches to patches" but, still, some dependency between patches. And ability to define simple order by 01-02-… is most ease way to solve this. But this can be added later, in case we'll really have these dependencies between patches.

**Comment by vonydev** [comment]
Done.
I've added the matrixssl_initialization also.

**Comment by powerman** [comment]
> Done.

Sadly there are still some reverted changes:

- https://github.com/powerman/perl-Crypt-MatrixSSL3/pull/14/files#diff-5d3ba18294715d9415e9e732852bfec6L314
- https://github.com/powerman/perl-Crypt-MatrixSSL3/pull/14/files#diff-5d3ba18294715d9415e9e732852bfec6L330
- https://github.com/powerman/perl-Crypt-MatrixSSL3/pull/14/files#diff-6c7db5dcd46c60e48378e62c33c35aeaL770 and related changes like https://github.com/powerman/perl-Crypt-MatrixSSL3/pull/14/files#diff-6c7db5dcd46c60e48378e62c33c35aeaL780 and below
- https://github.com/powerman/perl-Crypt-MatrixSSL3/pull/14/files#diff-6c7db5dcd46c60e48378e62c33c35aeaL831
- there are also some other changes in whitespaces, but they may be intentional

Other issues:
- https://github.com/powerman/perl-Crypt-MatrixSSL3/pull/14/files#diff-5d3ba18294715d9415e9e732852bfec6R443 duplicated line added, same as below

**Comment by vonydev** [comment]
Fixed - I've removed some blank lines before/after directives (#if, #endif) because on some system XS stops working - a known bug.

**Comment by powerman** [comment]
Thanks!

**Pull request merged**
